### ISSUE TITLE
Programmi Elettorali

### ISSUE THREAD

**Issue by iltempe** [HackForItaly/politicamentecorretto#10]
Inserire qui sotto i link ai programmi elettorali che avete reperito. Grazie

**Comment by cristigalas** [comment]
@iltempe facendo una piccola ricerca sui programmi elettorali online ecco cosa ho trovato:
- **5stelle** ha pubblicato qui http://www.movimento5stelle.it/programma/index.html un testo programmatico diviso per temi. In calce ad ogni tema si precisa che il programma è stato votato da tot iscritti e c’è un link che rimanda ad un pdf con un testo. Tuttavia nel Pdf si specifica che si tratta di un “programma parziale” risalente a luglio 2017.
- **Potere al popolo** ha pubblicato il suo programma in 15 punti qui https://poterealpopolo.org/potere-al-popolo/programma/
- **Liberi e uguali** non ha nemmeno un sito ma su quello di Sinistra italiana c’è un elenco di “contributi al programma” di Leu suddiviso per temi: http://www.sinistraitaliana.si/liberi-uguali-lassemblea-programma-scuola-universita-ricerca-beni-culturali/ Nessuna traccia di programma nemmeno sul sito di Grasso.
- **Partito democratico**: sul sito del Pd e di Renzi non c’è traccia del programma.
- **Forza Italia**: sul sito nessun programma, se non questa paginetta non datata http://www.forzaitalia.it/notizie/11764/-pronto-il-cantiere-delle-idee-e-del-programma
- **Lega**: sul sito nessuna traccia di programma ma c’è una sezione “Politiche 2018” in cui sono pubblicati una serie di manifesti con una sorta di slogan e parole d’ordine su alcuni temi http://www.leganord.org/il-movimento/politiche-2018
- **Fratelli d’Italia**: sul sito alla voce programma c’è questo testo non datato (Tesi di Trieste): http://www.fratelli-italia.it/le-tesi-trieste/ Ma in un’altra sezione “Le Sfide per l’Italia” c’è un altro documento programmatico (non datato) in 16 punti http://www.fratelli-italia.it/le-sfide-per-l-italia-9-gennaio-pomeriggio/

**Comment by cristigalas** [comment]
Segnalo questa importante **normativa introdotta dalla nuova legge elettorale**, pubblicata oggi da [RaiNews](http://www.rainews.it/dl/rainews/articoli/Elezioni-on-line-la-guida-al-voto-del-Viminale-ecco-tutte-le-novita-245cf8da-77ec-4a88-b2e8-22c84cae79ea.html):

_L'articolo 4 della nuova legge elettorale prevede che in un'apposita sezione del sito web del ministero dell'interno (denominata "Elezioni trasparenti") siano pubblicati - entro 10 giorni dalla scadenza del termine per il deposito del contrassegno - per ciascun partito, movimento e gruppo politico che abbia presentato liste il contrassegno depositato, lo statuto e il *programma elettorale* con nome e cognome del capo della forza politica._

Visto che il termine per la presentazione dei contrassegni è il 19-20-21 gennaio, i programmi elettorali dovrebbero essere sul sito del Ministero entro il 31 gennaio.

**Comment by gbartalesi** [comment]
questo è un piccolo partito che sta cercando di raccogliere firme. 
ma il programma è già online
http://www.diecivoltemeglio.com/programma#1

**Comment by iltempe** [comment]
nelle pagine del programma del movimento 5 stelle è programma è questo:
![image](https://user-images.githubusercontent.com/6368214/35007942-51eda6a8-fafb-11e7-95a7-92c9067678ee.png)

**Comment by favoeva** [comment]
lista +europa nessun programma pubblicato al momento http://www.radicali.it/campagne/piueuropa/

**Comment by iltempe** [comment]
ho inziato a creare un dataset qui https://github.com/HackForItaly/politicamentecorretto/blob/master/_data/programmi.yml ampliate pure. almeno non perdiamo informazioni.
