### ISSUE TITLE
Disqus non viene caricato

### ISSUE THREAD

**Issue by aborruso** [HackForItaly/politicamentecorretto#17]
C'è probabilmente da creare l'account dedicato

![immagine](https://user-images.githubusercontent.com/30607/34931727-7e246918-f9d0-11e7-9378-fd4db8d1761c.png)

**Comment by iltempe** [comment]
l'account l'ho avevo creato. Il name è politicamentecorretto e il link al profilo è http://disqus.com/by/politicamentecorretto1

**Comment by aborruso** [comment]
ok @iltempe . Segnalo che se apri qui https://unapromessa.it/issues/14/, disqus non funziona.

**Comment by iltempe** [comment]
fatto.
