### ISSUE TITLE
Logo e nome di Italia a Fuoco quando si condivide il sito sui social

### ISSUE THREAD

**Issue by cristigalas** [HackForItaly/politicamentecorretto#21]
Quando si condivide sui social il link www.unapromessa.it nell'anteprima compare l'iconcina di Italia a Fuoco e il titolo "Italia a Fuoco", invece che logo e nome di Politicamente corretto.

**Comment by iltempe** [comment]
su quale social accade? su facebook funziona bene mi pare.

**Comment by cristigalas** [comment]
Telegram e Twitter... vedi ad esempio [qui ](https://twitter.com/todarolorenzo/status/952823145534296065) e [qui ](https://t.me/politicamentecorretto/3).

**Comment by iltempe** [comment]
@cristigalas dovrebbe essere tutto ok, fammi sapere che poi chiudo.

**Comment by cristigalas** [comment]
Sembra ancora non funzionare sia su Twitter che su Telegram :(
![184cabd4-4717-4c86-8817-674e7cb86e38](https://user-images.githubusercontent.com/21283775/34965015-58d680ca-fa51-11e7-8a5c-9aa576234478.jpeg)
![56df8b38-6756-450f-862c-eead07bef371](https://user-images.githubusercontent.com/21283775/34965016-58f28a36-fa51-11e7-8968-d0fa5046d9fa.jpeg)

**Comment by aborruso** [comment]
Dovrei avere risolto.

Per twitter ho usato https://cards-dev.twitter.com/validator

Per Telegram @WebpageBot

**Comment by cristigalas** [comment]
@aborruso ho provato anch’io e adesso funziona!
