### ISSUE TITLE
Pagina Promesse

### ISSUE THREAD

**Issue by iltempe** [HackForItaly/politicamentecorretto#24]
Dove pubblichiamo le promesse già raccolte? Nelle pagine degli eventi? in una pagina a sè stante? ditemi come la vedete...

**Comment by cristigalas** [comment]
@iltempe io pensavo che sarebbero state pubblicate nella sezione già esistente “Elezioni” (distinguendo tra Politiche e Regionali) ed era per quello che chiedevo di ragionare meglio sui titoli e i menù... ma forse non ho capito bene la struttura del sito... 
Comunque, secondo me, pubblicare le promesse già raccolte è una priorità perché solo così chi arriva sul sito capisce come funziona e possiamo fare dei tweet mirati che aiutino a far conoscere il progetto...

**Comment by favoeva** [comment]
Concordo . Inizierei a organizzare label 
Primo livello
Nazionali
Regionali

Secondo livello
Singole liste che si presentano

**Comment by iltempe** [comment]
Proposta:
La pagina riporta i dati di un evento esempio "nazionali 2018" all'interno della pagina dividiamo per Indice delle Promesse e dei Programmi di quell'evento (a sua volta cliccabili per visualizzarli singolarmente)

**Comment by cristigalas** [comment]
@iltempe ok e l’evento “nazionali 2018” sta nella sezione “Elezioni”? Io però chiamerei l’evento “Politiche 2018”, è più corretto.

**Comment by iltempe** [comment]
ho creato la collection "eventi" e dentro ci ho messo regionali e nazionali. Potremmo creare un layout unico per entrambi e farci gli indici all'interno. oppure sono a disposizione per suggerimenti qui è come viene adesso https://www.unapromessa.it/politiche_2018/

**Comment by cristigalas** [comment]
@iltempe e come funzionerebbe? Si clicca su Promesse o Programmi e si apre la pagina relativa con le singole segnalazioni oppure le segnalazioni sono tutte elencate nella pagina Politiche 2018 sotto le voci Promesse e Programmi? In questo secondo caso, significherebbe che se ci sono molte promesse (come spero) i Programmi finirebbero molto in fondo... non so se mi sono spiegata e soprattutto se ho capito la struttura che hai in mente. Forse conviene pubblicare le promesse e i programmi e vedere come viene...
