### ISSUE TITLE
Testo introduttivo form segnalazioni

### ISSUE THREAD

**Issue by cristigalas** [HackForItaly/politicamentecorretto#33]
@aborruso qui di seguito una proposta per il testo introduttivo pubblicato in testa alla [webform](https://enketo.ona.io/x/#pYFo):

_Una volta inviata la segnalazione, dopo circa 5 minuti, la vedrai pubblicata qui*. 
La redazione si occuperà di classificare e pubblicare le segnalazioni inviate, in modo da costruire un archivio strutturato utile per tracciare e monitorare le promesse elettorali dopo il voto.
Per facilitare la raccolta e il monitoraggio ti chiediamo di non segnalare promesse elettorali troppo generiche ma il più possibile specifiche e su temi precisi. Inoltre, ai fini del progetto, ti saremo grati se ogni segnalazione contenesse massimo 2 promesse elettorali, meglio una. Grazie!_

*[inserirei il link alla pagina del sito dove pubblicheremo le promesse elettorali e non a github, tanto poi in calce alla segnalazione ci sarà anche il link alla issue]

**Comment by aborruso** [comment]
Grazie @cristigalas 

Il link alla pagina non c'è, perché ancora quella pagina non esiste. Ma non appena ci sarà, faremo come suggerisci.

Fatto

![immagine](https://user-images.githubusercontent.com/30607/35053316-0ce3e766-fbaa-11e7-8409-a0ba32b2898f.png)

**Comment by aborruso** [comment]
c'è errore ...

**Comment by aborruso** [comment]
corretto

**Comment by cristigalas** [comment]
Ottimo, grazie @aborruso!
