### ISSUE TITLE
Centro destra: prime proposte della coalizione (in attesa del programma)

### ISSUE THREAD

**Issue by favoeva** [HackForItaly/politicamentecorretto#35]
Nome: 'Centro destra: prime proposte della coalizione'
data: 15/01/2018
Nome fonte: 'Il Post'
urlfonte: 'http://www.ilpost.it/2018/01/08/coalizione-centrodestra-elezioni-2018/'
dichiarazione: 'Dopo una lunga riunione organizzata domenica 7 gennaio ad Arcore – Forza Italia ha ufficializzato la formazione di una coalizione con Lega, Fratelli d’Italia e “quarto Polo” in vista delle prossime elezioni politiche e delle regionali. Come scrive Il Post, per ora non sono state date molte notizie sul programma dell’intesa, a parte un elenco dei punti comuni diffuso al termine dell’incontro, senza dettagli su modi e tempi per realizzarli: 
• meno tasse e burocrazia; 
• più aiuti a chi ha bisogno; 
• più sicurezza per tutti; 
• revisione della Legge Fornero; 
• adeguamento delle pensioni minime a 1.000 euro; 
• valorizzazione del Made in Italy; 
• realizzazione della flat tax; 
• controllo dell’immigrazione.'
id: '24074781'

**Comment by gdemartino** [comment]
La sensazione è che la coalizione abbia un programma, poi le singole forze politiche abbiamo programmi più "spinti" a seconda del proprio elettorato: 
Questo è quello di **Fratelli d'Italia**, caricato proprio oggi:
http://www.fratelli-italia.it/wp-content/uploads/2018/01/FDI-Programma-in-15-punti-19.01.2017.pdf
Il programma è diviso in 15 punti, spiccano slogan come "no allo ius soli" e "prima gli italiani".
Questo è quello di **Forza Italia**, che al primo posto mette la riduzione delle tasse:
https://www.tecnicadellascuola.it/wp-content/uploads/2018/01/Programma-centrodestra-condiviso-10-PUNTI-FORZA-ITALIA.pdf
La Lega non ancora pervenuta
