### ISSUE TITLE
hangout 2018-01-18: cambiare le licenze di questo progetto in cc by sa

### ISSUE THREAD

**Issue by aborruso** [HackForItaly/politicamentecorretto#44]
La licenza di wikipedia è virale e usiamo anche dati wikipedia, quindi dobbiamo portare tutto a https://creativecommons.org/licenses/by-sa/3.0/

**Comment by iltempe** [comment]
@aborruso serve anche citare wikipedia in qualche modo particolare?

**Comment by iltempe** [comment]
@aborruso ho cambiato la licenza ovunque fosse citata, aggiornato la pagina opendata con le licenze https://www.unapromessa.it/opendata/. Avrei anche aggiornato le note "legali del sito" che ho messo online (c'è dentro licenza, la cookie policy, trattamento dei dati etc...). https://www.unapromessa.it/legal/ Se non devo aggiungere altro chiudo.

**Comment by iltempe** [comment]
ci siamo chiariti in chat. ho fatto. chiudo.
