### ISSUE TITLE
eliminare categoria Ambiente da pagina https://www.unapromessa.it/promessa/

### ISSUE THREAD

**Issue by favoeva** [HackForItaly/politicamentecorretto#56]
https://www.unapromessa.it/promessa/
![cattura](https://user-images.githubusercontent.com/9965333/35186214-ec915f20-fe10-11e7-89ea-522da2ad63bb.PNG)

**Comment by favoeva** [comment]
questa categoria/label è stata accorpata a Territorio

**Comment by iltempe** [comment]
fatto.
