### ISSUE TITLE
Correlare le promesse Contro Altre promesse

### ISSUE THREAD

**Issue by iltempe** [HackForItaly/politicamentecorretto#58]
Sarebbe interessante per ogni promessa valutare se ce ne sono alcune CONTRARIE quella. Interessante anche per la valutazione delle "famose" coalizioni.

**Comment by mfortini** [comment]
Per prima cosa bisogna inserire in ciascuna promessa eventuali promesse correlate. Se si potesse farlo nello yaml sarebbe la cosa più veloce.
esempio:
<pre>
commenti:
    - 12
    - 25
    - 81
</pre>

**Comment by iltempe** [comment]
io userei la funzionalità nativa di github che consente di correlare le promesse. tipo tramite un commento dove si mette # + il numero della promessa correlata

**Comment by mfortini** [comment]
Sarebbe stato molto più comodo, ho dovuto usare lo yaml perché gestire i collegamenti da jekyll significava analizzare il body della issue per cercare un insieme # + numero che non è compreso fra i filtri esistenti (almeno che io sappia)

**Comment by aborruso** [comment]
Vedi https://github.com/HackForItaly/politicamentecorretto/wiki/promesse-collegate
