### ISSUE TITLE
Funzione Ricerca

### ISSUE THREAD

**Issue by iltempe** [HackForItaly/politicamentecorretto#59]
Sarebbe utile poter effettuare ricerca per
- politico
- partito
- tema
- parola (?)

che dite?

**Comment by cristigalas** [comment]
Concordo! Più aumentano le promesse e più è necessario un campo ricerca. Tipo quello che è in Tci.

**Comment by cristigalas** [comment]
@iltempe @mfortini @aborruso la funzione ricerca sul sito sta diventando sempre più necessaria, anche per evitare l'invio di promesse doppie, tanto più che nella form abbiamo aggiunto una raccomandazione che invita gli utenti a verificare, prima dell'invio, che una promessa non sia già presente.

**Comment by aborruso** [comment]
Io in questi giorni non me ne posso occupare :(

**Comment by cristigalas** [comment]
va bene @aborruso, se non c'è nessun altro che lo può fare aspetteremo ;)

**Comment by iltempe** [comment]
Un primo prototipo. accetto suggerimenti. https://www.unapromessa.it/searchissues/

**Comment by aborruso** [comment]
@iltempe ho cercato `settimane` e non ottengo nulla. È normale?

![immagine](https://user-images.githubusercontent.com/30607/36372288-e38e0cf0-1564-11e8-9e51-820008ac2c9d.png)

**Comment by iltempe** [comment]
@aborruso si era normale. Nel senso che non cercavo nella descrizione. ho aggiunto la ricerca anche in quel campo e (per il momento) tolto le categorie. https://www.unapromessa.it/searchissues/ mi pare che adesso vada piuttosto benino. ho altre due o tre miglioramenti in testa. con calma li faccio.

**Comment by aborruso** [comment]
Grazie!!
