### ISSUE TITLE
refuso in pagina collabora

### ISSUE THREAD

**Issue by giuragu** [HackForItaly/politicamentecorretto#6]
Ciao @iltempe, @aborruso, @mfortini  con una scusa vi faccio i complimenti per questa fantastica idea....e vi segnalo un refuso nella pagia [collabora](https://unapromessa.it/collabora/) dove leggo al secondo punto "tramite scrivendo una mail". Sarebbe da eliminare la parole "tramite". Ancora complimenti

**Comment by iltempe** [comment]
Grazie @giuragu ho fixato la pagina. Ovviamente attendiamo le tue segnalazioni!
