### ISSUE TITLE
Cambiare file di riferimento per anagrafica e nome campo

### ISSUE THREAD

**Issue by aborruso** [HackForItaly/politicamentecorretto#60]
Caro @mfortini ho scritto una guida per la redazione https://github.com/HackForItaly/politicamentecorretto/wiki/anagrafica-unapromessa

Ho introdotto un nuovo campo, perché noi estendiamo everypolitician e l'ho chiamato `unapromessaID`.

C'è un nuovo JSON che si aggiorna ogni ora a questo URL http://dev.ondata.it/projs/people/andy/unapromessa/unapromessa.json, con la struttura di sotto.

Il campo di riferimento quindi diventa `unapromessaID`. Appena puoi dovresti cambiare il template e la chiamata alla sorgente dati.

Grazie

```JSON
 {
    "wikidata": "Q266651",
    "unapromessaID": "UQ266651",
    "twitter": "mara_carfagna",
    "nome": "CARFAGNA Maria Rosaria",
    "wikipediaIT": "https://it.wikipedia.org/wiki/Mara_Carfagna",
    "immagine": "http://www.camera.it/application/xmanager/projects/leg17/attachments/shadow_deputato/has_fotos/000/301/531/original_d301531.jpg"
  }
```

**Comment by aborruso** [comment]
@mfortini vedo che ci stai lavorando. Un nota (penso inutile): il source image della foto profilo, prendiamola sempre da `immagine` di `unapromessa.json`.

Grazie

**Comment by mfortini** [comment]
sì sì fatto. Grazie a te
