### ISSUE TITLE
Aggiungere categoria tematica VARIE sul sito

### ISSUE THREAD

**Issue by cristigalas** [HackForItaly/politicamentecorretto#61]
Alcune promesse elettorali, come [questa qui](https://github.com/HackForItaly/politicamentecorretto_data/issues/41), non hanno una categoria tematica e dunque non si visualizzino sul sito. Ho pensato allora di aggiungere una label VARIE ma andrebbe aggiunta questa categoria Varie anche nella [pagina](https://www.unapromessa.it/promessa/) del sito.

**Comment by iltempe** [comment]
fatto.
