### ISSUE TITLE
Call To Action

### ISSUE THREAD

**Issue by iltempe** [HackForItaly/politicamentecorretto#63]
Pensavo ad un post per chiamare direttamente qualche categoria a collaborare per popolare l'archivio:
- giornalisti
- politici
- politologi
- storici
- ???

Che dite? qualcuno può scrivere 10 righe?

**Comment by favoeva** [comment]
l'appello ai politici potrebbe funzionare bene attraverso mention dei loro account twitter, 
magari linkando una loro promessa già registrata sulla nostra piattaforma 

es. tweet 
"cara/o candidata/o @xxxxx da oggi questa (la) tua promessa elettorale è pubblicata qui in #opendata insieme a quelle di altri candidati sullo stesso tema https://twitter.com/politicacorr/status/955444135409979394. Se vuoi segnalarci altre tue promesse elettorali, puoi farlo attraverso questo form. Grazie"

**Comment by favoeva** [comment]
per quanto riguarda i giornalisti potremmo mandare mail, qui abbiamo quelli del Lazio già utilizzati per TCI https://docs.google.com/spreadsheets/d/1gvD6lblYsDPQDhcH8iYKtGculkSfqzk69M_aOsYLOjM/edit?usp=sharing

**Comment by cristigalas** [comment]
@favoeva io inizierei ad inviare tweet ai vari candidati con il testo che hai scritto e vediamo che succede, tra l'altro basterebbe modificare (a mano) il tweet che si genera cliccando sul tasto di condivisione social in calce alla promessa, così abbiamo anche già l'account twitter del candidato che Andrea ha inserito di default proprio oggi... Che ne dici?

**Comment by cristigalas** [comment]
@favoeva @iltempe comunque, secondo me, una sorta di appello a politici, giornalisti, attivisti, cittadini, ecc. potremmo farlo con il comunicato stampa che si era detto di preparare nel momento in cui il progetto fosse abbastanza avviato e per il quale Donata si era resa disponibile a darci una mano... Che ne dite?

**Comment by iltempe** [comment]
secondo me il progetto adesso è "abbastanza avviato"... ;-)

**Comment by cristigalas** [comment]
Allora chiediamo a Donata di raggiungerci qui e cominciare a buttare giù una bozza di comunicato?

**Comment by dontyna** [comment]
ciao cari, eccomi qui. @cristigalas serve ancora aiuto per il comunicato? Secondo me ora che siete arrivati a 100 promesse è il momento giusto.

**Comment by favoeva** [comment]
ciao @dontyna !
certo che sì... che ne dite di uscire oggi con un comunicato sulle nostre prime 100 e sulla questione scadenza deposito simboli e programmi?
( la scadenza per il deposito liste candidati è l'8 febbraio giusto @cristigalas ?)

**Comment by favoeva** [comment]
partirei anche con un tweet bombing magari di risposta ai tweet che carichiamo come promesse ... 
ES:"@mention da oggi questa (la) tua promessa elettorale è pubblicata qui in #opendata insieme a quelle di altri candidati sullo stesso tema https://twitter.com/politicacorr/status/955444135409979394. Puoi segnalarci le tue promesse su www.unapromessa.it."

**Comment by cristigalas** [comment]
@dontyna @favoeva scusate ma vi leggo solo ora.... Sì, secondo me è il momento di uscire con un comunicato stampa! Entro oggi il Viminale deve pubblicare sul sito simboli e programmi. Possiamo monitorare e vedere se lo fanno ed eventualmente se non fanno denunciare il ritardo. 
Per la lista dei candidati invece dobbiamo aspettare l'8 febbraio...
Ma intanto il comunicato lo preparerei e invierei, se riusciamo, entro un paio di giorni (con o senza accenno alla questione Viminale), che ne dite?

**Comment by cristigalas** [comment]
@favoeva sì, sì il tweet bombing con un testo tipo quello che scrivi va fatto!

**Comment by iltempe** [comment]
@dontyna io sarei per farlo un comunicato stampa. Il tempo mi pare buono ;-)

**Comment by dontyna** [comment]
Argh, non mi sono arrivate le notifiche, scusate! Se lo prepariamo oggi però lo manderei comunque lunedì, il venerdì non è un buon giorno. Serve una parte introduttiva del progetto, poi magari una dichiarazione di @aborruso @iltempe che spiegano perché è stato creato?

**Comment by cristigalas** [comment]
@dontyna ok Donata! Guardo nei post che abbiamo pubblicato sul sito se c'è qualcosa che possiamo riutilizzare per la parte introduttiva e semmai butto giù qualcosa. Poi credo sarebbe importante aggiungere anche una parte sui programmi elettorali in Archive.org e la possibilità di analizzarli in modo comparato facendo ricerche per parole (vedi #95).

**Comment by iltempe** [comment]
io lascio spazio ad @aborruso

**Comment by cristigalas** [comment]
@dontyna @favoeva ho buttato giù una bozza per il comunicato stampa riprendendo anche quanto @iltempe ha scritto nei post sul sito. La bozza [la trovate qui](https://docs.google.com/document/d/1N2Y2IbmAjWGtNlkuXKJEu1ZWdzDDcnbtBAx0IPXqwrU). In corsivo ho riportato alcuni estratti dai post già pubblicati che potrebbero essere utilizzati anche come dichiarazioni... È proprio una bozza ma sono sicura che voi due saprete trasformarla in un bel comunicato ;)

**Comment by iltempe** [comment]
chiudo?

**Comment by cristigalas** [comment]
Secondo me sì.
