### ISSUE TITLE
Come gestiamo le promesse simili? Pubblichiamo sempre e comunque?

### ISSUE THREAD

**Issue by cristigalas** [HackForItaly/politicamentecorretto#66]
Sono arrivate due promesse simili ad altre già pubblicate ma con fonti diverse (vedi https://github.com/HackForItaly/politicamentecorretto_data/issues/64 e https://github.com/HackForItaly/politicamentecorretto_data/issues/63). Che facciamo in questi casi? Pubblichiamo comunque e semmai le colleghiamo una all'altra quando ciò sarà possibile? Oppure ci limitiamo ad annotare nella scheda Github che esiste già una promessa simile e poi non accettiamo? (come facciamo ad esempio per le segnalazioni simili di Tci). Che ne pensi @favoeva?

Ho paura che se il progetto prende piede saranno molte le promesse simili... Io sarei quindi per non pubblicarle tutte ma selezionare quella più completa (o la prima inviata) e non accettare le altre, così da evitare confusione. Inoltre, quando sarà disponibile la funzione 'ricerca', nella form di segnalazione suggerisco di inserire una piccola nota in cui chiediamo agli utenti di verificare che la promessa non sia già pubblicata così da evitare inutili doppioni.

**Comment by cristigalas** [comment]
Proposta di @aborruso https://github.com/HackForItaly/politicamentecorretto_data/issues/63#issuecomment-359459983

**Comment by cristigalas** [comment]
Risolta. Chiudo.

**Comment by aborruso** [comment]
Ho aggiunto una nota importante https://github.com/HackForItaly/politicamentecorretto/wiki/promesse-collegate#nota-bene

L'ho fatto perché una promessa si era "rotta" ed era colpa dello spazio.
