### ISSUE TITLE
Moderazione su Facebook

### ISSUE THREAD

**Issue by iltempe** [HackForItaly/politicamentecorretto#76]
Nel gruppo Facebook Politicamente Corretto sta arrivando di tutto. andrebbe un minimo moderato ed eventualmente usato per creare segnalazioni da post nel gruppo stesso.

**Comment by favoeva** [comment]
chiudo perchè non avevo visto questa issue e ne ho aperta un'altra stesso tema , con proposte operative qui https://github.com/HackForItaly/politicamentecorretto/issues/78
