### ISSUE TITLE
Immagine di condivisione sui social

### ISSUE THREAD

**Issue by iltempe** [HackForItaly/politicamentecorretto#77]
E' possibile secondo voi fare in modo che quando si condivide una promessa su twitter, facebook e telegram come immagine associata venga la faccia del politico anzichè il logo del progetto?

**Comment by aborruso** [comment]
Twitter recupera quanto trova nell'head dell'HTML. Si può impostare un twitter card come quella di sotto

```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@politicacorr">
<meta name="twitter:title" content="Politicamente Corretto,  per raccogliere le promesse elettorali">
<meta name="twitter:description" content="Le promesse elettorali di Attilio #Fontana #Lega su controlli ambientali e manutenzioni stradali">
<meta name="twitter:image" content="http://www.camera.it/application/xmanager/projects/leg17/attachments/shadow_deputato/has_fotos/000/305/788/original_d305788.jpg">
```

**Comment by iltempe** [comment]
ma si può farlo dinamicamente? intendo dire come si fa a popolare dinamicamente il campo twitter:image in base al candidato della promessa?

**Comment by aborruso** [comment]
@iltempe scusami. Puoi prendere ispirazione da [qui](https://github.com/HackForItaly/politicamentecorretto/blob/master/_layouts/promessa.html#L47-L53): è il template della pagina della promesse.

In una condizione if viene fatto il check che verifica se al candidato è associato un valore nel campo `idItalia` di [questo JSON](https://github.com/HackForItaly/politicamentecorretto/blob/master/_data/unapromessa.json), e se sì viene stampato l'hyperlink alle attività parlamentari.

In questo caso deve essere aggiunta una condizione if, nel [file](https://github.com/HackForItaly/politicamentecorretto/blob/master/_includes/head.html) che gestisce il rendering dell'head.

**Comment by iltempe** [comment]
per ora su twittter è a poto. resta da vedere facebook e telegram che pero dovrebbero gestire i tag in modo diverso.

**Comment by iltempe** [comment]
mi pare che @mfortini abbia sistemato anche su facebook. chiudo.
