### ISSUE TITLE
La pubblicazione è ferma da 4 ore

### ISSUE THREAD

**Issue by aborruso** [HackForItaly/politicamentecorretto#81]
Vedi commit https://github.com/HackForItaly/politicamentecorretto/commits/master

**Comment by cristigalas** [comment]
Ma da ieri sera non ci sono state altre segnalazioni da pubblicare Adesso ne ho inviate qualcuna, le accetto e vediamo se le pubblica...

**Comment by aborruso** [comment]
Chiudo, eranon non approvate.

Scusate
