### ISSUE TITLE
Funzione "Vedi le ultime promesse pubblicate"

### ISSUE THREAD

**Issue by cristigalas** [HackForItaly/politicamentecorretto#83]
Secondo me, oltre alla funzione ricerca, sul sito sarebbe molto utile avere la possibilità di individuare rapidamente le ultime promesse pubblicate. Che ne dite?

**Comment by iltempe** [comment]
ecco una pagina di prova con le ultime promesse. https://unapromessa.it/last/

**Comment by cristigalas** [comment]
Ottimo! Per me va benissimo. 
Come dicevamo in chat segnalerei la pagina con un bottone in home e anche nella pagina delle promesse così lo vede anche chi atterra direttamente su quella pagina. Che ne dite?
Domanda: quante ultime promesse inseriresti? Le ultime 6 come sono nella pagina ora? O potremmo arrivare a 10?

**Comment by aborruso** [comment]
Ottimo rendiamo disponibile, almeni in menu, questa pagina.

Io farei che il default del menu "promesse elettorali" è sempre last, e poi un sottomenu di "promesse elettorali" chiamato "per categoria".

**Comment by iltempe** [comment]
Ho fatto due voci sul menu promesse una con le promesse più recenti, una per categoria. Chiudo qui questo issue.
