### ISSUE TITLE
Una pagina che listi le promesse per data di pubblicazione decrescente

### ISSUE THREAD

**Issue by aborruso** [HackForItaly/politicamentecorretto#86]
Se apro la pagina promesse, vedo sempre `Ambiente e territorio`. 

Mi piacerebbe che ci fosse anche una modalità (anche un'altra pagina) da usare per vedere sempre le ultime promesse pubblicate

**Comment by iltempe** [comment]
tipo un #83 ?

**Comment by iltempe** [comment]
Ho messo in piedi la pagina con le ultime promesse elettorali. attualmente se ne vedono solo 6 ma possiamo aumentare e diminuire. Inoltre a questo punto possiamo ad esempio metterle in home page. https://unapromessa.it/last/ che ne dici?

**Comment by aborruso** [comment]
chiudo si continua su #83
