### ISSUE TITLE
La sezione "Elezioni Trasparenti" del Ministero dell'interno è online

### ISSUE THREAD

**Issue by giuragu** [HackForItaly/politicamentecorretto#92]
Eccola [qui](http://dait.interno.gov.it/elezioni/trasparenza). Ricordavo però ci dovessero esser anche le liste o sbaglio? Magari sono in corso di pubblicazione. Attualmente mancano comunque alcuni programmi...

**Comment by aborruso** [comment]
Scaricato ieri qui https://github.com/HackForItaly/politicamentecorretto_data/tree/master/elezioniTrasparenza :)

**Comment by giuragu** [comment]
Grazie @aborruso. Non avevo visto scusa :)

**Comment by aborruso** [comment]
@giuragu colpa mia, che non ne ho dato visibilità
